# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-11 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=196)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=31)),
                ('image', pyuploadcare.dj.models.ImageField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('technologies', models.CharField(blank=True, max_length=200)),
                ('livesite', models.CharField(max_length=200)),
                ('githublink', models.CharField(max_length=200)),
            ],
        ),
    ]
